### ISSUE TITLE
Github Issue, PR & contribution template(s)

### ISSUE THREAD

**Issue by Lewiscowles1986** [mroderick/plete#54]
👋 RE: https://github.com/mroderick/plete-docs/issues/8

Do you think this could benefit from issue template(s) / PR template(s)?

Sometimes it can help gaining actionable & useful feedback.

It is pretty fully featured now so IDK.

**Comment by mroderick** [comment]
I think those would be a great idea. Pull requests welcome!

We have some templates in https://github.com/sinonjs/sinon, as well as contribution guidelines. Feel free to use those (or others) as inspiration.

**Comment by Lewiscowles1986** [comment]
* [ ] issue template(s)
* [ ] PR template
* [ ] Contribution guidelines

**Comment by mroderick** [comment]
#57 has been merged. Does that complete the list?

**Comment by Lewiscowles1986** [comment]
Thank you @mroderick and @hexeberlin 🙏 thank you both.
