### ISSUE TITLE
Escape input string before using its characters in a RegExp pattern

### ISSUE THREAD

**Issue by mathiasbynens** [mroderick/plete#6]
https://github.com/mroderick/plete/blob/4d754fc012512931b1f946cd53aa81a74a84691f/lib/filter.js#L8-L9

In the demo for example, you can currently enter `S.a.n` and see `Spain` suggested.

**Comment by mroderick** [comment]
Thank you for reporting this!

**Comment by mroderick** [comment]
This has been fixed in `plete@0.2.3`
